### ISSUE TITLE
getNext on pagingObject for PlaylistTracks failing

### ISSUE THREAD

**Issue by kinshukJ** [Daltron/Spartan#1]
Thank you for creating such an awesome Spotify Client! There's a small issue with getNext being called on a pagingObject dealing with tracks fetched for a playlist. Spartan.getPlaylistTracks() works fine and loads 20 tracks. However after retrieving the pagingObject and calling getNext on it I get `fatal error: unexpectedly found nil while unwrapping an Optional value
2017-07-09 19:55:16.220157-0500 Sink[12993:3968613] fatal error: unexpectedly found nil while unwrapping an Optional value`. To confirm I called getNext right after fetching the pagingObject as follows ` let _ = Spartan.getPlaylistTracks(userId: userId, playlistId: playlistId, success: { (tracksPage) in
            
            if tracksPage.canMakeNextRequest {
                tracksPage.getNext(success: { (trackpage) in
                    print("successfully fetched \(trackpage)")
                }, failure: { (error) in
                    print(error.description)
                    print(error.errorMessage)
                })
            }
             //completionHandler(tracksPage)
        }) { (error) in
            print(error.description)
            print(error.errorMessage)
        }
` and I get the error. I've also attached the stack trace below. 

I am quite certain you'd be able to recreate the error if you fetch tracks for playlist that has number of songs over the the limit of 1 pagingObject and calling getNext on the pagingObject. Any fix or direction would be greatly appreciated!

<img width="1220" alt="screen shot 2017-07-09 at 7 56 24 pm" src="https://user-images.githubusercontent.com/8029879/27999251-bbed5460-64e0-11e7-9f1a-e1673120f405.png">

**Comment by Daltron** [comment]
Hi @kinshukJ! 😄 Thanks for providing such a detailed issue! I have fixed this in the v1.0.2 release! All you need to do is run `pod update` and you should be good to go! Thanks again! 👍

**Comment by kinshukJ** [comment]
Thanks for such a speedy fix Daltron!

**Comment by kinshukJ** [comment]
Hi Daltron, it doesn't give an error, however it doesn't load more tracks either. The paging object I get after calling getNext on it returns the same set of the first 20 tracks. Any direction or update would be much appreciated!

**Comment by Daltron** [comment]
@kinshukJ I just tried to reproduce and am unable to. I have a playlist with a lot of tracks and `getNext` is returning the next set of tracks without any issues. Can you provide a code example that shows the error?

**Comment by kinshukJ** [comment]
My bad Daltron. It was a thread issue. It's all fixed and working :). Thanks again!
