### ISSUE TITLE
Retrying requests that fail due to network time outs

### ISSUE THREAD

**Issue by RudyB** [Daltron/Spartan#10]
I have been noticing request time out issues with Spartan specifically when the user's device network reachability status changes. I recommend that you add support for the [Alamofire `RequestRetrier` protocol](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#requestretrier) that allows the session manager to automatically retry requests if they fail for a specific reason.

**Comment by Daltron** [comment]
Hi @RudyB! 😄 Feel free to open up a pull request!

**Comment by RudyB** [comment]
@Daltron see #11
