### ISSUE TITLE
Issue with getArtists()

### ISSUE THREAD

**Issue by darrellshi** [Daltron/Spartan#2]
The getArtists() function returns a list of "Album"s.

**Comment by Daltron** [comment]
Hi @darrellshi ! 😄 I have fixed this in the v1.0.2 release! All you need to do is run `pod update` and you should be good to go! Thanks for bringing this to my attention! 👍

**Comment by darrellshi** [comment]
Hi Dalton,

Thank you for fixing the issue so quickly!

Darrell Shi
_____________________________
